# Generated by Django 2.2.3 on 2019-07-23 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('name', models.TextField(primary_key=True, serialize=False)),
                ('housetype', models.TextField()),
                ('kind_of_news', models.TextField()),
                ('images', models.TextField(null=True)),
                ('etc', models.TextField(null=True)),
            ],
        ),
    ]
